

local DrRayLibrary = loadstring(game:HttpGet("https://raw.githubusercontent.com/AZYsGithub/DrRay-UI-Library/main/DrRay.lua"))()
local window = DrRayLibrary:Load("⚔️ LUCKY GUYS ⚔️", "Default")

local tab = DrRayLibrary.newTab("FISH FUNCTION", "ImageIdHere")

tab.newToggle("AUTO FISHING", "🦈 Let's go get a fishing rod 🦈", false, function(Fishing1)
_G.Fishing = Fishing1
   while _G.Fishing do wait()
        local args = {
    [1] = "bind",
    [2] = Vector3.new(196.26263427734375, 1.149999976158142, 103.15097045898438)
}

game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(184.531, 16.6495, 119.906)
game:GetService("Players").LocalPlayer.Character.FishingRod.LocalScript.RemoteFunction:InvokeServer(unpack(args))
    end
end)

tab.newToggle("AUTO EQUIP FISHINGROD", "", false, function(auto)
_G.Autoequip = auto
end)

spawn(function()
Weapon = "FishingRod"
while wait() do
if _G.Autoequip then
pcall(function()
game.Players.LocalPlayer.Character.Humanoid:EquipTool(game:GetService("Players").LocalPlayer.Backpack:FindFirstChild(Weapon))
end)
end
end
end)
tab.newToggle("AUTO INVENTORY ITEM EVENT", "", false, function(autoin)
_G.autoin = autoin
while wait() do
if _G.autoin then
-- Script generated by SimpleSpy - credits to exx#9394
 
local args = {
    [1] = "Change",
    [2] = "Water bowl",
    [3] = "Backpack"
}
 
game:GetService("ReplicatedStorage").Inventory:FireServer(unpack(args))
 
-- Script generated by SimpleSpy - credits to exx#9394
 
local args = {
    [1] = "Change",
    [2] = "Blood Curse",
    [3] = "Backpack"
}
 
game:GetService("ReplicatedStorage").Inventory:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394
 
local args = {
    [1] = "Change",
    [2] = "Skateboard",
    [3] = "Backpack"
}
 
game:GetService("ReplicatedStorage").Inventory:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394
 
local args = {
    [1] = "Change",
    [2] = "Blade Kagenou",
    [3] = "Backpack"
}
 
game:GetService("ReplicatedStorage").Inventory:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394
 
local args = {
    [1] = "Change",
    [2] = "Orb Shadow",
    [3] = "Backpack"
}
 
game:GetService("ReplicatedStorage").Inventory:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394
 
local args = {
    [1] = "Change",
    [2] = "Orb Rainbow",
    [3] = "Backpack"
}
 
game:GetService("ReplicatedStorage").Inventory:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394
 
local args = {
    [1] = "Change",
    [2] = "Fire Curse",
    [3] = "Backpack"
}
 
game:GetService("ReplicatedStorage").Inventory:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394
 
local args = {
    [1] = "Change",
    [2] = "Tail Dinosaur",
    [3] = "Backpack"
}
 
game:GetService("ReplicatedStorage").Inventory:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394
 
local args = {
    [1] = "Change",
    [2] = "Orb Dragon",
    [3] = "Backpack"
}
 
game:GetService("ReplicatedStorage").Inventory:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394
 
local args = {
    [1] = "Change",
    [2] = "Camera",
    [3] = "Backpack"
}
 
game:GetService("ReplicatedStorage").Inventory:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394
 
local args = {
    [1] = "Change",
    [2] = "Cane",
    [3] = "Backpack"
}
 
game:GetService("ReplicatedStorage").Inventory:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394
 
local args = {
    [1] = "Change",
    [2] = "Cake",
    [3] = "Backpack"
}
 
game:GetService("ReplicatedStorage").Inventory:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394
 
local args = {
    [1] = "Change",
    [2] = "Grimoire",
    [3] = "Backpack"
}
 
game:GetService("ReplicatedStorage").Inventory:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394
 
local args = {
    [1] = "Change",
    [2] = "Orb Beast",
    [3] = "Backpack"
}
 
game:GetService("ReplicatedStorage").Inventory:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394
 
local args = {
    [1] = "Change",
    [2] = "Heart Demon",
    [3] = "Backpack"
}
 
game:GetService("ReplicatedStorage").Inventory:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394
 
local args = {
    [1] = "Change",
    [2] = "Candy Pumpkin",
    [3] = "Backpack"
}
 
game:GetService("ReplicatedStorage").Inventory:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394
 
local args = {
    [1] = "Change",
    [2] = "Fish",
    [3] = "Backpack"
}
 
game:GetService("ReplicatedStorage").Inventory:FireServer(unpack(args))
 
 local args = {
    [1] = "Change",
    [2] = "Gokumonkyo",
    [3] = "Backpack"
}
 
game:GetService("ReplicatedStorage").Inventory:FireServer(unpack(args))
     end
   end
end)
